name: "Push Generate Docs"
on: 
  push:
    branches: 
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make html"
        docs-folder: "docs/"
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-xetex texlive-latex-extra texlive-fonts-recommended fonts-freefont-otf"
        build-command: "make latexpdf"
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationPDFSpecification
        path: docs/_build/latex/
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/kc1awv/M17_spec.git --branch gh-pages --single-branch gh-pages
        git clone https://github.com/M17-Project/M17_spec.git
        cp -r docs/_build/html/* gh-pages/
        cp -r docs/_build/latex/M17Protocol*.pdf gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "smiller@kc1awv.net"
        git config --local user.name "kc1awv"
        git add .
        git commit -m "Update PDF documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GH_TOKEN }}
    # ===============================
